version: '3.2'
services:

  ubuntu20:
    image: giffy/ubuntu_base20:latest
    container_name: ubuntu_base20
    hostname: ubuntu20
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1g
    volumes:
      - /tmp:/tmp
      - ./data:/data
