version: '3.2'
services:

  homarr:
    # https://homarr.dev/docs/getting-started/installation/
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    hostname: homarr
    restart: unless-stopped
    
    volumes:
      - ./homarr/configs:/app/data/configs
      - ./homarr/icons:/app/public/icons
      - ./homarr/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Madrid
      - DISABLE_ANALYTICS="true"
    ports:
      - '3575:7575'