version: '3.2'
services:

  portainer:
    #image: portainer/portainer-ce:alpine
    image: portainer/portainer-ce:2.22.0

    container_name: portainer
    ports:
      - "9443:9443"
    networks:
      - portainer_network

  portainer_agent:
    image: portainer/agent:2.19.4
    container_name: portainer_agent
    environment:
      - AGENT_CLUSTER_ADDR=tasks.portainer_agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer_network

networks:
  portainer_network:
